### ISSUE TITLE
Input with "\" bugs

### ISSUE THREAD

**Issue by tonowoe** [NullVoxPopuli/emberclear#51]
If you send a message:

`\|`

Output will be:

`|`

Or `\\\\` will be `\\`.

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

what is the desired output?

Also, the text box is markdown, so markdown by default interprets \\ as an escape character.
Maybe documentation could go somewhere to explain that?

How do other markdown-enabled chats handle that

**Comment by tonowoe** [comment]
I thought it's a bug because it gets triggered only in certain special characters. For example:
`\a` => `\a`
`\!` => `!`
`\-` => `-`
`\v` => `\v`

Also `#` acts weirdly (is this intended?):
`#test` => `test`
`#!` => `!`

**Comment by NullVoxPopuli** [comment]
So, ultimately, this is showdown:
https://github.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/package.json#L45 : Project Page: https://github.com/showdownjs/showdown/

I think the `#` makes more sense, because it means "header" -- at least at the start of a line.

These rules apply here as well:

`# header` =>

# header

`\a` => \a
`\!` => \!
`\-` => \-
`\v` => \v



are you wanting to type things with more backslashes? If there is a strong enough use case, there can maybe be a mode to disable markdown conversion

**Comment by tonowoe** [comment]
I think it should work like it works in Discord and [Whatsapp](https://faq.whatsapp.com/sw/general/26000002). Italic, bold, strikethrough and code block with _ * ~ and ```.

**Comment by NullVoxPopuli** [comment]
What's the current behavior with those?

**Comment by tonowoe** [comment]
It's OK, but I would prefer not to have those showdown markup things, just leave it to _ * ~ ```.

**Comment by NullVoxPopuli** [comment]
I guess, what's the use case for wanting to keep `\` in the message?

**Comment by tonowoe** [comment]
I guess there can be many use cases for that. I was writing some regex rules to my friend without code block and saw that ```\``` char was making the rule bugging. But generally I just think it's weird if some chars are stripped out which are not even the markup chars ( _ * ~ ```).

**Comment by tonowoe** [comment]
Hmm tbh now after testing I'm not 100% sure what would be the best way.

In Whatsapp (asterisk is for bold in Whatsapp):
![whatsapp](https://upload.vaa.red/i/2gmJkZ.png)

In Whatsapp it just ignores `\`

**Comment by NullVoxPopuli** [comment]
closing, cause I don't think this is _that_ important :-\
