### ISSUE TITLE
Question: Discord-esque moderation and comparison with Matrix/Riot

### ISSUE THREAD

**Issue by DonaldTsang** [NullVoxPopuli/emberclear#764]
So EmberClear has claimed that it can replace Discord but does it have good moderation?
Also how is this better than Matrix and Riot since this is also FOSS?

**Comment by NullVoxPopuli** [comment]
> So EmberClear has claimed that it can replace Discord

has it? where?

> does it have good moderation?

emberclear doesn't _yet_ have channels -- right now there is just direct messaging. However, channels are what @halawami, @CelticMajora , @GreenMobius , and @amgassert are working on ;)

They're mostly working on the fundamentals of channels with some basic democracy-based moderation. Logic can later then be added to have better moderation -- but we need to prove that democracy-based moderation can exist in a way that is both distributed non-persistent (the goal shtick of emberclear).

> how is this better than Matrix and Riot 

Riot has many many more features than emberclear does at the moment -- because it has a lot more resources working on. 
However, emberclear is in a different space than most popular chat apps today -- there is no persistence -- no server.
Matrix accounts (which, for others reading here, is the backing protocol / technology behind Riot), are required to be persisted, and use a traditional username/password.

For more comparisons, here is a spreadsheet comparing a bunch of features: https://docs.google.com/spreadsheets/d/116MpTXfga_f8N0tLSY_Glt_fd4GIag9T5-P_mag7RlQ/edit?usp=sharing

**Comment by DonaldTsang** [comment]
> They're mostly working on the fundamentals of channels with some basic democracy-based moderation. 

I would like to see the allowance of hub-and-spoke moderation system as well, if you know what I mean

> has it? where?
> For more comparisons, here is a spreadsheet comparing a bunch of features: https://docs.google.com/spreadsheets/d/116MpTXfga_f8N0tLSY_Glt_fd4GIag9T5-P_mag7RlQ/edit?usp=sharing

Ahhh...

**Comment by NullVoxPopuli** [comment]
> hub-and-spoke moderation system as well, if you know what I mean

potentially -- but for clarity, could you elaborate?

> Also BTW what about https://github.com/qTox/qTox ?

Doesn't look like there is a web/browser version -- after some research, I'm not sure if there can be? because most of things are written in Go, and Go doesn't run on the web.

I do like their readme though: https://github.com/qTox/qTox/blob/master/README.md#qtox
I should update the readme for emberclear based on some of these ideas.
Security-wise, qTox is no different from emberclear.

I'm still trying to find out what a `Tox` node does, once I find that out, I'll have a clearer picture of how it compares to the goals of emberclear.

**Comment by DonaldTsang** [comment]
> potentially -- but for clarity, could you elaborate?

I think the term "centralized moderation" is overkill, but basically a non-democracy based, but rather trust or consensus based moderation with "organs of governance" (some moderating text, some do announcements, some do PR, some actually do development).

**Comment by NullVoxPopuli** [comment]
Closing for now. If you have further related questions, feel free to reopen ;)
